feat: enhance release process with version synchronization and simplified workflow

diff --git a/docker/Dockerfile b/docker/Dockerfile
--- a/docker/Dockerfile
+++ b/docker/Dockerfile
@@ -1,8 +1,8 @@
-
-FROM ghcr.io/humlab-swedeb/swedeb_frontend:latest AS frontend-dist
+ARG FRONTEND_VERSION=latest
+FROM ghcr.io/humlab-swedeb/swedeb_frontend:${FRONTEND_VERSION} AS frontend-dist
 
 #####################################################################################
-# Final stage (final)
+# Stage 2: Final application image
 #####################################################################################
 
 FROM ghcr.io/humlab-swedeb/swedeb/cwb:3.5.0 as final
@@ -12,36 +12,26 @@ LABEL maintainer="Roger Mähler <roger dot mahler at umu dot se>"
 ENV APP_USER=cwbuser
 ENV APP_UID=1021
 ENV APP_GID=1021
+ENV PYTHONDONTWRITEBYTECODE 1
+ENV PYTHONUNBUFFERED 1
 
 USER root
 
-RUN mkdir -p /data/cwb/data /data/corpus/tagged_frames /data/corpus/dtm /data/corpus/metadata
+RUN mkdir -p /app /data/cwb/data /data/corpus/tagged_frames /data/corpus/dtm /data/corpus/metadata
 
 WORKDIR /app
 
-ARG SWEDEB_BACKEND_SOURCE="pypi"
+COPY --chown=${APP_USER}:${APP_USER} main.py .
+COPY --chown=${APP_USER}:${APP_USER} entrypoint.sh .
+COPY --chown=${APP_USER}:${APP_USER} config ./config/
+COPY --chown=${APP_USER}:${APP_USER} --from=frontend-dist /app/public ./public
+COPY --chown=${APP_USER}:${APP_USER} dist/*.whl ./
 
-# Copying entire context to /context (note that dist might be missing)
-COPY . /context
-COPY --from=frontend-dist /app/public ./public
-
-RUN set -e && \
-    if [ -d /context/dist ]; then \
-        mv /context/dist /backend-wheels/ ; \
-    fi && \
-    mv /context/main.py /app/main.py && \
-    mv /context/entrypoint.sh /app/entrypoint.sh && \
-    mv /context/config /app/config && \
-    pip3 install /wheels/*.whl; \
-    if [ "${SWEDEB_BACKEND_SOURCE}" == "pypi" ]; then \
-        pip3 install "api_swedeb==${SWEDEB_BACKEND_TAG}"; \
-    elif [ "${SWEDEB_BACKEND_SOURCE}" == "whl" ]; then \
-        pip3 install /backend-wheels/api_swedeb-"${SWEDEB_BACKEND_TAG}"-py3-none-any.whl && \
-        rm -rf /backend-wheels; \
-    fi && \
-    chown -R ${APP_USER}:${APP_USER} /app /data && \
-    chmod +x entrypoint.sh && \
-    rm -rf /context /wheels /backend-wheels /tmp/*
+RUN set -ex; \
+    pip install --no-cache-dir ./*.whl; \
+    chown -R ${APP_USER}:${APP_USER} /data; \
+    chmod +x entrypoint.sh; \
+    rm ./*.whl # Clean up the wheel after installation
 
 USER ${APP_USER}
 
